<a href="https://colab.research.google.com/github/QZKasoma-Luo/CUDA-ImageClassifier/blob/main/save_cpu.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd
from matplotlib import pyplot as plt
import time

data = pd.read_csv('train.csv')
data = np.array(data)
m, n = data.shape
np.random.shuffle(data) # shuffle before splitting into dev and training sets

data_dev = data[0:1000].T
Y_dev = data_dev[0]
X_dev = data_dev[1:n]
X_dev = X_dev / 255.

data_train = data[1000:m].T
Y_train = data_train[0]
X_train = data_train[1:n]
X_train = X_train / 255.
_,m_train = X_train.shape
def init_params():
    W1 = np.random.rand(10, 784) - 0.5
    b1 = np.random.rand(10, 1) - 0.5
    W2 = np.random.rand(10, 10) - 0.5
    b2 = np.random.rand(10, 1) - 0.5
    return W1, b1, W2, b2

def ReLU(Z):
    return np.maximum(Z, 0)

def softmax(Z):
    A = np.exp(Z) / sum(np.exp(Z))
    return A

def forward_prop(W1, b1, W2, b2, X):
    Z1 = W1.dot(X) + b1
    A1 = ReLU(Z1)
    Z2 = W2.dot(A1) + b2
    A2 = softmax(Z2)
    return Z1, A1, Z2, A2

def ReLU_deriv(Z):
    return Z > 0

def one_hot(Y):
    one_hot_Y = np.zeros((Y.size, Y.max() + 1))
    one_hot_Y[np.arange(Y.size), Y] = 1
    one_hot_Y = one_hot_Y.T
    return one_hot_Y

def backward_prop(Z1, A1, Z2, A2, W1, W2, X, Y):
    one_hot_Y = one_hot(Y)
    dZ2 = A2 - one_hot_Y
    dW2 = 1 / m * dZ2.dot(A1.T)
    db2 = 1 / m * np.sum(dZ2)
    dZ1 = W2.T.dot(dZ2) * ReLU_deriv(Z1)
    dW1 = 1 / m * dZ1.dot(X.T)
    db1 = 1 / m * np.sum(dZ1)
    return dW1, db1, dW2, db2

def update_params(W1, b1, W2, b2, dW1, db1, dW2, db2, alpha):
    W1 = W1 - alpha * dW1
    b1 = b1 - alpha * db1
    W2 = W2 - alpha * dW2
    b2 = b2 - alpha * db2
    return W1, b1, W2, b2
def get_predictions(A2):
    return np.argmax(A2, 0)

def get_accuracy(predictions, Y):
    print(predictions, Y)
    return np.sum(predictions == Y) / Y.size

def gradient_descent(X, Y, alpha, iterations):
    W1, b1, W2, b2 = init_params()
    for i in range(iterations):
        Z1, A1, Z2, A2 = forward_prop(W1, b1, W2, b2, X)
        dW1, db1, dW2, db2 = backward_prop(Z1, A1, Z2, A2, W1, W2, X, Y)
        W1, b1, W2, b2 = update_params(W1, b1, W2, b2, dW1, db1, dW2, db2, alpha)
        if i % 10 == 0:
            print("Iteration: ", i)
            predictions = get_predictions(A2)
            print(get_accuracy(predictions, Y))
    return W1, b1, W2, b2
time_s_cpu = time.time()
W1, b1, W2, b2 = gradient_descent(X_train, Y_train, 0.10, 500)
time_e_cpu = time.time()
print("Time cpu taken: ", time_e_cpu - time_s_cpu)

Iteration:  0
[6 0 0 ... 7 0 1] [8 9 2 ... 8 1 4]
0.1135609756097561
Iteration:  10
[6 6 2 ... 7 2 8] [8 9 2 ... 8 1 4]
0.20402439024390243
Iteration:  20
[6 6 2 ... 7 1 8] [8 9 2 ... 8 1 4]
0.28448780487804876
Iteration:  30
[6 6 2 ... 7 1 8] [8 9 2 ... 8 1 4]
0.33639024390243905
Iteration:  40
[5 6 5 ... 7 1 8] [8 9 2 ... 8 1 4]
0.3768780487804878
Iteration:  50
[5 6 5 ... 7 1 8] [8 9 2 ... 8 1 4]
0.41248780487804876
Iteration:  60
[5 7 5 ... 8 1 8] [8 9 2 ... 8 1 4]
0.4478536585365854
Iteration:  70
[5 7 5 ... 8 1 8] [8 9 2 ... 8 1 4]
0.49102439024390243
Iteration:  80
[5 7 5 ... 8 1 9] [8 9 2 ... 8 1 4]
0.5211707317073171
Iteration:  90
[5 7 5 ... 8 1 9] [8 9 2 ... 8 1 4]
0.5510243902439025
Iteration:  100
[5 4 5 ... 8 1 9] [8 9 2 ... 8 1 4]
0.577170731707317
Iteration:  110
[5 4 5 ... 8 1 9] [8 9 2 ... 8 1 4]
0.5989512195121951
Iteration:  120
[5 4 5 ... 8 1 9] [8 9 2 ... 8 1 4]
0.619390243902439
Iteration:  130
[5 4 5 ... 8 1 9] [8 9 2 ... 8 1 4]
0.6380243902439025
Iteration:  14